### ISSUE TITLE
Formalize funders

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#12]
looking at 
```python
            dict_fund = {"funderName": contr_el.name}
            if contr_el.identifier:
                dict_fund["funderIdentifier"] = contr_el.identifier
```
of #6 we nohow regulate yet specification of funders.

I remember zenodo having some way although a "fragile" one... we have in datalad's .zenodo.json:
```
    "grants": [
        {
            "id": "10.13039/100000001::1429999"
        }
    ],
```
where `10.13039/100000001` corresponds to NSF (sending a PR to list more! ;)) although I don't think DOI service knows about that... seems to boil to https://www.openaire.eu/claim-publication which is EU specific and not yet "generalized". I wonder if there is some "dictionary" of funders or alike to make those identifiers "linkable"

<details>
<summary>more info on zenodo's grants:</summary> 

https://developers.zenodo.org/#representation  somewhere has:

List of OpenAIRE-supported grants, which have funded the research for this deposition. Each array element is an object with the attributes:
* id: grant ID.

Example: [{'id':'283595'}] (European Commission grants only)
or funder DOI-prefixed: [{'id': '10.13039/501100000780::283595'}] (All grants, recommended)

Accepted funder DOI prefixes:
Australian Research Council: 10.13039/501100000923
Austrian Science Fund: 10.13039/501100002428
European Commission: 10.13039/501100000780
European Environment Agency: 10.13039/501100000806
Academy of Finland: 10.13039/501100002341
Hrvatska Zaklada za Znanost: 10.13039/501100004488
Fundação para a Ciência e a Tecnologia: 10.13039/501100001871
Ministarstvo Prosvete, Nauke i Tehnološkog Razvoja: 10.13039/501100004564
Ministarstvo Znanosti, Obrazovanja i Sporta: 10.13039/501100006588
National Health and Medical Research Council: 10.13039/501100000925
National Institutes of Health: 10.13039/100000002
National Science Foundation: 10.13039/100000001
Nederlandse Organisatie voor Wetenschappelijk Onderzoek: 10.13039/501100003246
Research Councils: 10.13039/501100000690
Schweizerischer Nationalfonds zur Förderung der wissenschaftlichen Forschung: 10.13039/501100001711
Science Foundation Ireland: 10.13039/501100001602
Wellcome Trust: 10.13039/100004440
</details>

**Comment by satra** [comment]
we have contributors who are funders/sponsors

**Comment by yarikoptic** [comment]
I have got that. In #6 you even allow for funder to be also some other type of contributor (yet to see that to be pragmatically useful or a sign of a data entry mistake). The main point for this issue: we do not standardize reference to funding agencies beyond may be name (e.g. NIH or NSF).

**Comment by satra** [comment]
we do through use of ror for identifier. but it is optional (e.g., https://ror.org/04t0s7x83). this is also where we would need to provide search functionality via the meditor to fill in these fields.

**Comment by yarikoptic** [comment]
oh nice, thanks! Let's consider resolved!
