### ISSUE TITLE
export to datacite: do not silently skip authors without ,

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#16]
ref: https://github.com/dandi/dandischema/pull/6/files#r638982211

should be either an `assert` or at least some logging so we do not just silently drop data

**Comment by satra** [comment]
the only input to this is a `PublishedDandiset` object, which you cannot create without validation (well technically you can, but we don't expect people who use the to_datacite to do so :) ) 

so such an assertion should not be necessary. what i think is important perhaps is to allow for variations:

```
In [6]: family, first = re.findall(r"^([\w\s\-]+)?,\s+([\w\s\-\.]+)?$", "Chan, Kong-sangå").pop()
   ...: 

In [7]: family
Out[7]: 'Chan'

In [8]: first
Out[8]: 'Kong-sangå'
```

**Comment by satra** [comment]
i will update the check.
