### ISSUE TITLE
workflow for releasing library [and schema]

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#2]
Continuing on https://github.com/dandi/dandi-cli/issues/638#issuecomment-845224089 
Since we ended up with a library, it should have its own versioning from schema version.  But it somewhat brings us a full circle to the motivation behind https://github.com/dandi/dandi-cli/issues/638 -- automate and harmonize (have staging etc) schema releases...

observation: **any new schema release should trigger library release** (since it would provide all the pydantic "interface" to that schema), **but not wise versa** (we can release library patches and big changes to API etc without changing anything to schema).

I am trying to wrap my head around what should be our workflow here. I guess we can 

- use `auto` labels etc for regular library releasing (all the `minor`, `major` etc labels)
- schema version change will require manual change of `DANDI_SCHEMA_VERSION`
- we dedicate tags with `schema-{DANDI_SCHEMA_VERSION}` to annotate releases which change the schema
- both client and schema (if current `{DANDI_SCHEMA_VERSION}` was not released) will be released upon merge of the PR marked for `release`:
  - library **can** be released without making a new release of schema
  - schema **cannot** be released without release of the library
  - PR marked with `release` label should get extra test to ensure that `DANDI_SCHEMA_VERSION` schema was not yet released (e.g. by testing for presence of `schema-{DANDI_SCHEMA_VERSION}` tag and/or looking into exported schemas, and fail otherwise.
    - note: `DANDI_SCHEMA_VERSION` might be incremented in some prior PR which was not marked for `release`
    - we need to re-trigger tests if labels change on a PR
    - we need to protect `master` branch to not allow untested/failing PRs (yet to see if feasible given possible codecov "complaints")
- no `release` of library should be allowed if it changes already released schema: extra check to be added to `release` workflow for paranoid @yarikoptic.
WDYT @satra and @jwodder ?

**Comment by satra** [comment]
i agree with observation/assertion.

i think github-actions can trigger a re-check if a label is changed (added/removed). this is how conda-forge does a rerender.

**Comment by yarikoptic** [comment]
Recheck might be insufficient if I just quickly click merge after adding release label. But I guess it also shouldn't hurt , so let's do that too.

**Comment by yarikoptic** [comment]
no better ideas came to mind, so let's proceed with the outlined here plan

**Comment by jwodder** [comment]
@yarikoptic 

> we dedicate tags with schema-{DANDI_SCHEMA_VERSION} to annotate releases which change the schema

Would this be done manually?

> alternative could be (if way to do with auto, @jwodder ?) to populate labels schema-{major,minor,patch} and do automagically boost DANDI_SCHEMA_VERSION upon release if any PRs since prior release have those

I don't believe this is feasible.

> no release of library should be allowed if it changes already released schema.

How exactly do you want this enforced?  We already have a workflow for checking that released schemata aren't modified.  Is it sufficient to just manually check that this test passes before merging?

**Comment by satra** [comment]
the schema version should still come from the constants in the library. there are too many considerations for schema change to automatically determine major/minor/patch.

> We already have a workflow for checking that released schemata aren't modified. Is it sufficient to just manually check that this test passes before merging?

such a failure could prevent merge.

**Comment by yarikoptic** [comment]
since "I don't believe this is feasible." I would not worry about ` schema-{DANDI_SCHEMA_VERSION} ` labels... I crossed out that entry

**Comment by satra** [comment]
also schema versions are being used to do migration checks. i would leave schema versions in the code instead of labeling.

regarding the publish schema workflow. that workflow could trigger on release instead of on master. and merge can be held back if changes would not increment schema version relative to released versions. this latter check should be done after merging master.

**Comment by jwodder** [comment]
> regarding the publish schema workflow. that workflow could trigger on release instead of on master.

Actually, it can't.  In order to prevent infinite loops, events performed using a GitHub Actions token (such as `auto`'s creation of GitHub releases) do not trigger workflow events.

>  merge can be held back if changes would not increment schema version relative to released versions. this latter check should be done after merging master.

How would merge be "held back" if the check happens after merging?

**Comment by jwodder** [comment]
@yarikoptic I think you crossed out the wrong item.

**Comment by satra** [comment]
> How would merge be "held back" if the check happens after merging?

the check should happen before merging as part of a PR's workflow.

**Comment by jwodder** [comment]
@satra Do you want GitHub to prevent merging if the test doesn't pass?  I don't think there's a way to do that without breaking `auto` and its pushes to master.

**Comment by satra** [comment]
but auto would push only if release tag is there **and** merge is clicked, right?

so this would enable/disable merge based on the schema_check_workflow , which would:
-  merge master
- generating schema
- check for diffs relative to last release
- if diff, look for new version is greater than old release
- if all good, then pass

**Comment by satra** [comment]
> enabling a branch protection rule to block merge of failing PRs would also disabling directly pushing to master

ah, in the short term we can rely on humans then, but would be good to see if this can be done.

**Comment by satra** [comment]
branch protections may still work:

![image](https://user-images.githubusercontent.com/184063/119535389-eeba7900-bd55-11eb-825c-afe13a3dc993.png)


this should just make status checks prevent a merge, but should not prevent a push into the protected branch. we can test by enabling this and then pushing something to the main branch without a PR.

**Comment by yarikoptic** [comment]
> @yarikoptic I think you crossed out the wrong item.

indeed ;) fixed now

**Comment by yarikoptic** [comment]
@jwodder I have tuned up top level description to my current understanding of the desired workflow. @satra please chime in if I had missed anything

**Comment by satra** [comment]
> both schema and client will be released upon merge of the PR marked for release:

i would say client will be released upon merge of PR marked for release. schema is also updated if necessary.

**Comment by jwodder** [comment]
@yarikoptic 

> we dedicate tags with `schema-{DANDI_SCHEMA_VERSION}` to annotate releases which change the schema

Do you want these tags to be automated?

> library can be released without making a new release of schema

> PR marked with `release` label should get extra test to ensure that `DANDI_SCHEMA_VERSION` schema was not yet released

These requirements appear to be conflicting.  New versions of the library can only be released via the `release` label, and if they can be released without making a new schema version, then they're sometimes going to have the same `DANDI_SCHEMA_VERSION` as a previous library version.

> we need to protect master branch to not allow untested/failing PRs

I don't believe this is possible.  [`auto`'s documentation](https://intuit.github.io/auto/docs/build-platforms/github-actions#running-with-branch-protection) indicates that using branch protection with `auto` will require the use of an admin token, which means that the branch protection rules must not be applied to admins, but since all three of us are admins on this repo, we wouldn't be affected by the automated blocking of merges.

**Comment by yarikoptic** [comment]
> > both schema and client will be released upon merge of the PR marked for release:
> 
> i would say client will be released upon merge of PR marked for release. schema is also updated if necessary.

you are right -- my description was not specific enough since indeed schema might not need a release.  "updated" is not specific enough to my taste either... made it into

- both client and schema (if current `{DANDI_SCHEMA_VERSION}` was not released) will be released upon merge of the PR marked for `release`:

**Comment by yarikoptic** [comment]
@jwodder 

> > we dedicate tags with `schema-{DANDI_SCHEMA_VERSION}` to annotate releases which change the schema
> 
> Do you want these tags to be automated?

yes . Should be Annotated tags.  Message should mention which version of library corresponds to that version of schema

> > library can be released without making a new release of schema
> 
> > PR marked with `release` label should get extra test to ensure that `DANDI_SCHEMA_VERSION` schema was not yet released
> 
> These requirements appear to be conflicting. New versions of the library can only be released via the `release` label, and if they can be released without making a new schema version, then they're sometimes going to have the same `DANDI_SCHEMA_VERSION` as a previous library version.

that is ok.  Imagine we fixed a bug in code which does not affect schema or improved documentation - we release library, but schema version stays the same and indeed could be the one "provided" by multiple versions of the library.

> > we need to protect master branch to not allow untested/failing PRs
> 
> I don't believe this is possible. [`auto`'s documentation](https://intuit.github.io/auto/docs/build-platforms/github-actions#running-with-branch-protection) indicates that using branch protection with `auto` will require the use of an admin token, which means that the branch protection rules must not be applied to admins, but since all three of us are admins on this repo, we wouldn't be affected by the automated blocking of merges.

We can dandibot as non-admin user, and use its token. @satra in https://github.com/dandi/dandischema/pull/6#issuecomment-847498577 you say that you added a token.  Was it from your user?

**Comment by yarikoptic** [comment]
> > > we need to protect master branch to not allow untested/failing PRs
> > 
> > 
> > I don't believe this is possible. [`auto`'s documentation](https://intuit.github.io/auto/docs/build-platforms/github-actions#running-with-branch-protection) indicates that using branch protection with `auto` will require the use of an admin token, which means that the branch protection rules must not be applied to admins, but since all three of us are admins on this repo, we wouldn't be affected by the automated blocking of merges.
> 
> We can dandibot as non-admin user, and use its token. @satra in [#6 (comment)](https://github.com/dandi/dandischema/pull/6#issuecomment-847498577) you say that you added a token. Was it from your user?

I think I have misjudged situation... So we do need a token from admin user but you saying that it "would not save us", correct?  I think it would provide sufficient feedback (failing workflow) and even though indeed we could click Merge never the less.  But I think it would prevent PRs from others to get the same treatment, right!  may be then we could even make only dandibot to be admin here and us some regular mortals too? ;)

**Comment by jwodder** [comment]
@yarikoptic Summary:

* If a PR does not have the `release` label, just run basic tests as normal.
* If a PR does have the `release` label, additionally test that no pre-existing schemata in dandi/schema would be modified by publishing.
* When the release workflow runs (which happens whenever a PR is merged and one or more PRs merged since the last release have the `release` label):
    * First test again that no pre-existing schemata are modified, and cancel the release if any would be.
    * After a successful release, if the schema version was incremented, publish the new schema and create a new tag.

Aside from the branch protection issue, am I leaving anything out?

**Comment by jwodder** [comment]
@yarikoptic 

> may be then we could even make only dandibot to be admin here and us some regular mortals too? ;)

I considered that, but we're organization owners, so the only role we can be assigned in this repo is "Admin" (and if we don't assign a role to any of us, I don't believe we'd have permission to merge any PRs).

**Comment by yarikoptic** [comment]
> Aside from the branch protection issue, am I leaving anything out?

I think it covers it well.  May be just missing the

- we need to re-trigger tests if labels change on a PR

trigger for PR tests if possible to do.

**Comment by yarikoptic** [comment]
> @yarikoptic
> 
> > may be then we could even make only dandibot to be admin here and us some regular mortals too? ;)
> 
> I considered that, but we're organization owners, so the only role we can be assigned in this repo is "Admin" (and if we don't assign a role to any of us, I don't believe we'd have permission to merge any PRs).

well, let's add it and see how it looks from our mighty admin or poor dandibot (or other mortal) account.

**Comment by jwodder** [comment]
@yarikoptic I just realized there's a problem with the currently-proposed setup:`schema-$VERSION` tags will be picked up by versioneer, leading to invalid project versions.  This can be fixed by prefixing all of the library version tags with `v` and configuring versioneer to filter for that prefix.

**Comment by yarikoptic** [comment]
isn't it possible to specify the glob, not just a prefix 
```
$> git describe                 
schema-0.4.0

$> git describe --match '[0-9]*'
0.2.0
```

**Comment by yarikoptic** [comment]
apparently it doesn't: https://github.com/python-versioneer/python-versioneer/pull/105

make prefix `0.` for now.  we will fix versoineer by we reach `1.`  ;-)

**Comment by yarikoptic** [comment]
I was blind there and duplicated my shortsightedness here... it should just work since prefix is passed directly as `--match`
```
$> git grep -e --match
src/git/from_vcs.py:                                     "--match", "%s*" % tag_prefix],
```
