### ISSUE TITLE
setup downstream testing of dandi-cli

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#21]
modularization comes at costs :-/ tests started to fail in dandi-cli.   Filed https://github.com/dandi/dandi-cli/pull/650 to pin it

I think we should introduce downstream testing there against dandi-cli .  With `~=` pining might need to do some dances? may be not with the explicit `pip install -e dandi-cli/` -- pip is too forgiving ;)).  That might be tainting our desire to merge only clean PRs here though.

wild idea is to autosend a PR whenever new .minor version of dandischema does not ruin dandi-cli which still relies on older one.  But I think it would be overkill

WDYT @jwodder @satra ?

**Comment by jwodder** [comment]
Given the new version restriction in dandi-cli, trying to install both it and the latest dandischema together likely won't work.  I think having the release workflow create a PR in dandi-cli for updating the version requirement and then seeing how the tests play out may be the way to go.

**Comment by yarikoptic** [comment]
> Given the new version restriction in dandi-cli, trying to install both it and the latest dandischema together likely won't work

if `pip` resists -- nothing a quick `sed -i '' -e` couldn't fix ;) (`-i ''` for Mac OSX, `-i` is ok as is on GNU)

> I think having the release workflow create a PR in dandi-cli for updating the version requirement and then seeing how the tests play out may be the way to go.

but it might be "too late": e.g. `.patch` release breaking dandi-cli but we would not know until after a release issuing that PR.

**Comment by yarikoptic** [comment]
> > Given the new version restriction in dandi-cli, trying to install both it and the latest dandischema together likely won't work
> 
> if `pip` resists -- nothing a quick `sed -i '' -e` couldn't fix ;) (`-i ''` for Mac OSX, `-i` is ok as is on GNU)

oh -- I had in mind testing against the development version of `dandi-cli` cloned first, but indeed makes more sense to test against released one as well if no `major` version boost label (if we follow #22).  If there is a major boost -- no need even to try I guess ;-)

**Comment by yarikoptic** [comment]
Wow time flies.  I still think it is a good idea ;-)
