### ISSUE TITLE
add branch protection rules and update auto config

### ISSUE THREAD

**Issue by satra** [dandi/dandischema#43]
`auto` does work with branch protection rules, it requires two things:

1. see here for the repo setup: https://github.com/neuronets/nobrainer/blob/master/.github/workflows/release.yml#L20
2. requires a personal access token instead of GITHUB_TOKEN

the one thing that i have not implemented in the nobrainer  yet is that the twine upload should only work if auto creates a new release, but not otherwise. i'll be looking into that soon.

**Comment by satra** [comment]
this PR separates out auto release and publish to pypi for nobrainer: https://github.com/neuronets/nobrainer/pull/156

**Comment by yarikoptic** [comment]
re token -- we have already `DANDI_GITHUB_TOKEN` secret which is what we use AFAIK.  Could you remind me (or may be @jwodder remembers?) what branch protection we need to add?

**Comment by satra** [comment]
merge only through PR and keep branch up to date with master. those have both been useful in other projects.

**Comment by yarikoptic** [comment]
Great, thank you! @jwodder please have a look to add those protections here.

**Comment by jwodder** [comment]
@satra @yarikoptic Here are the branch protection options.  Exactly which ones do you want enabled?

<img width="886" alt="Screen Shot 2021-06-22 at 13 12 17" src="https://user-images.githubusercontent.com/98207/122970144-8910db00-d35b-11eb-84a3-3ec0ba1c6840.png">

**Comment by satra** [comment]
![image](https://user-images.githubusercontent.com/184063/122970495-02103280-d35c-11eb-817e-8e06c3502899.png)

**Comment by jwodder** [comment]
@satra What status checks should be required?  I can't get GitHub Actions to come up in the search box.

**Comment by satra** [comment]
perhaps `test` and the release check?

**Comment by jwodder** [comment]
@satra By "the release check," do you mean the one from `test-schema.yml`?

**Comment by satra** [comment]
yes  the names of the checks are the names of the github actions inside the yaml files.

**Comment by jwodder** [comment]
Branch protection rule for `master` created.
