### ISSUE TITLE
should we get a common class (BioAgent?) for Participant and Contributor?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#54]
so e.g. to be able to identify datasets which have participants which are also contributors?

With ipdandi (interplanetary dandi) we might even have optional `species` in such a base class ;-)

**Comment by satra** [comment]
i don't think so at this point. the dandi schema is not how i would have modeled it, but was created to maintain some semblance to schema.org and datacite. happy to discuss details of data modeling that could work, but for the moment i would say this would be done through common ids/identifiers.

**Comment by yarikoptic** [comment]
ok
