### ISSUE TITLE
Move dandi-etag related logic from dand-cli to dandischema

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#57]
Per @satra 's thinking and my approval nodding -- rationale is

- to lighten up dandi-api dependencies (ATM depends on dandi-cli) for PartGenerator . 
  - Not sure if that is the only component which should be moved or entire `dandietag` -- most likely entire
  - dandi-api already depends on dandischema
- to avoid deadlock of dandi-api wanting a newer dandischema and now needing to wait for newer dandi-cli which would support it
- kinda makes sense since `dandischema` is the one desiring dandi-etag

Functionality should be first copied to dandischema and removed only later, whenever dandi-cli depends on this newer dandischema released version

**Comment by jwodder** [comment]
@yarikoptic Should the functionality be moved to `dandschema/core/digests/dandietag.py` (as it is in dandi-cli) or something with fewer intermediate directories?

**Comment by satra** [comment]
@jwodder - you could drop core if you want in this case.
