### ISSUE TITLE
Make dandi-cli tests run against dandi-api which uses this branch/PR version of dandischema

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandischema#62]
The idea came up from https://github.com/dandi/dandischema/pull/60#issuecomment-883632368 .  ATM, me and @satra guess, that dandi-cli uses `pip` installed version of dandi-api which `pip install`s dandischema from pypi.  We should make that container (probably could be done "post-hoc" in a fixture?) to install dandischema in question (current branch as `master` or the PR) and thus make dandi-api not refuse current possibly new version  of dandischema.  Tests might indeed then fail - but that would be the point of the test against dandi-cli to discover whenever new dandischema would break dandi-cli or the functionality of dandi-api which dandi-cli triggers.

**Comment by jwodder** [comment]
For the record, dandi-cli tests against a dandi-api image built from the latest commit to dandi-api's master branch.
