### ISSUE TITLE
Fail validation if no contributor is set as a contact

### ISSUE THREAD

**Issue by waxlamp** [dandi/dandischema#85]

**Comment by waxlamp** [comment]
@satra, @yarik, is this right?

**Comment by satra** [comment]
that is correct. and i believe this happens on the pydantic side of validation.

**Comment by waxlamp** [comment]
Right, it's possible this issue is actually a no-op; I was expecting to see a "no contact" message set on [this dandiset](https://deploy-preview-857--gui-dandiarchive-org.netlify.app/#/dandiset/000018) but it's not there, maybe because it's an earlier version of the schema.

**Comment by satra** [comment]
i have a feeling this has other errors (like bad name format) that are superseding the contact person error. 

the current release has this validation in place (and i suspect that's been there for a while)
https://github.com/dandi/dandischema/blob/3696446d225bf140273efcc90a908294f02b153e/dandischema/models.py#L963

just a note, that the contact person error would only be picked up by server side validation, not the jsonschema.

**Comment by djarecka** [comment]
I think that the name had a bad format indeed, and we had some cryptic regex error. But at the end there was no contact person, so perhaps better error could help

**Comment by waxlamp** [comment]
> I think that the name had a bad format indeed, and we had some cryptic regex error. But at the end there was no contact person, so perhaps better error could help

Not only that, but I believe *both* errors should show when there's no contact person set.

I would say this issue, as written, can be closed. But there's maybe a larger thing to accomplish here, which is that as many "parallel" errors as possible should show up when validation fails. I'll close this now, and if it needs to be worked on we can re-open. As for showing more errors, I think there's already some thinking about that happening so I'll leave it alone for the moment.
